### ISSUE TITLE
`users_list_group` and `users_list_group` are documented but not used (still using `users_group_vars` and `users_host_vars`)

### ISSUE THREAD

**Issue by PierreBeucher** [arillso/ansible.users#7]
Ansible var `users_list_group` and `users_list_group` are documented documented in as list of user and exists as default, but is never used in role. According to [CHANGELOG.md](https://github.com/arillso/ansible.users/blob/master/CHANGELOG.md):

> change var users_host_vars to users_list_host
> change var users_group_vars to users_list_group

However [related PR](https://github.com/arillso/ansible.users/pull/1) left old variables intact in tasks despite changing default and README

**Comment by sbaerlocher** [comment]
Hello @PierreBeucher,

Thank you for your patience and for bringing up the issue with the users_list_group variables in the ansible.users role. We are pleased to inform you that this issue has been addressed and resolved in our updated Ansible role available at https://github.com/arillso/ansible.system/tree/main/roles/users.

We encourage you to check out the new role, which should align with the documented variables and offer enhanced functionality.

Thank you for contributing to the improvement of our projects.

Best regards
